apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      name: hello-api
      labels:
        app: hello-api
    spec:
      containers:
        - name: hello-api
          # imagePullPolicy: Never
          image: dauh/hello-api:latest
          ports:
            - containerPort: 8080
              name: hello-api-svc
          # env:
          # - name: DATABASE_URL
          #   valueFrom:
          #     configMapKeyRef:
          #       name: hello-api
          #       key: database_url
          # - name: DATABASE_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: redis-cluster
          #       key: redis-password
          #       optional: false