apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-configmap
spec:
  template:
    metadata:
      labels:
        app: hello-configmap
    spec:
      containers:
        - name: hello-configmap
          image: docker.io/dauh/hello-api:22
          ports:
            - containerPort: 8083
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: hello-configmap