apiVersion: v1
kind: Service
metadata:
  name: microservice-svc
  labels:
    app: hello-configmap-microservice
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: hello-configmap-pod