name: CI Checks

on: [push]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Copy Files
        run: |
              mkdir artifacts
              cp api artifacts/.

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
            name: api
            path: artifacts